# Generated by Django 3.2.10 on 2022-01-28 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2BPayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(blank=True, max_length=12, null=True)),
                ('TransID', models.CharField(blank=True, max_length=12, null=True)),
                ('TransTime', models.CharField(blank=True, max_length=14, null=True)),
                ('TransAmount', models.CharField(blank=True, max_length=12, null=True)),
                ('BusinessShortCode', models.CharField(blank=True, max_length=6, null=True)),
                ('BillRefNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('InvoiceNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('OrgAccountBalance', models.CharField(blank=True, max_length=12, null=True)),
                ('ThirdPartyTransID', models.CharField(blank=True, max_length=20, null=True)),
                ('MSISDN', models.CharField(blank=True, max_length=12, null=True)),
                ('FirstName', models.CharField(blank=True, max_length=20, null=True)),
                ('MiddleName', models.CharField(blank=True, max_length=20, null=True)),
                ('LastName', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='Balance',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='CheckoutRequestID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='MerchantRequestID',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='MpesaReceiptNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='ResultCode',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='ResultDesc',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='TransactionDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
