# Generated by Django 3.2.10 on 2022-01-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_auto_20220128_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='C2BPayments',
        ),
        migrations.RemoveField(
            model_name='lnmonline',
            name='Balance',
        ),
        migrations.AddField(
            model_name='lnmonline',
            name='Amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
